inherit_gem:
  defra_ruby_style:
    - default.yml
require:
  - rubocop-capybara
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

RSpec/DescribeClass:
  Exclude:
    - spec/features/*
    - spec/features/projects/*
    - spec/lib/tasks/*
    - spec/requests/response_headers_spec.rb

# TODO Resolve these legacy Rubocop offenses
Capybara/SpecificMatcher:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Rails/HelperInstanceVariable:
  Enabled: false
Rails/I18nLocaleTexts:
  Enabled: false
RSpec/EmptyExampleGroup:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/RepeatedDescription:
  Enabled: false
RSpec/NoExpectationExample:
  Enabled: false
RSpec/RepeatedExample:
  Enabled: false
