inherit_gem:
  defra_ruby_style:
    - default.yml
require:
  - rubocop-rails
  - rubocop-rspec

# TODO Resolve these legacy Rubocop offenses
Metrics/AbcSize:
  Enabled: false
Rails/HelperInstanceVariable:
  Enabled: false
RSpec/EmptyExampleGroup:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/RepeatedDescription:
  Enabled: false
RSpec/RepeatedExample:
  Enabled: false
