inherit_from: .rubocop_todo.yml

inherit_gem:
  defra_ruby_style:
    - default.yml
require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

RSpec/DescribeClass:
  Exclude:
    - spec/features/*
    - spec/features/projects/*
    - spec/lib/tasks/*
    - spec/requests/response_headers_spec.rb
