language: ruby
cache: bundler

rvm:
- 2.3.0

env:
  DEVISE_MAILER_SENDER=no-reply@example.org
  SECRET_KEY_BASE="d2f5fb09a9b95e74af0c86eae84961c4440a483487e3237097c69ddfb9f4aa3bd482c352074cfcff369df51dddbb40e01932fa89585ba7e421ff3e5d62e23338"

before_script:
  - cp $TRAVIS_BUILD_DIR/dotenv.travis $TRAVIS_BUILD_DIR/.env
  - cp $TRAVIS_BUILD_DIR/config/database.travis.yml $TRAVIS_BUILD_DIR/config/database.yml
  - bundle exec rake pafs_core:install:migrations
  - git config --global user.name "Travis Test"  # for overcommit
  - git config --global user.email travis@example.com  # for overcommit
  - BUNDLE_GEMFILE=.overcommit_gems.rb bundle install
  - BUNDLE_GEMFILE=.overcommit_gems.rb bundle exec overcommit --sign
  - BUNDLE_GEMFILE=.overcommit_gems.rb bundle exec overcommit --sign pre-commit

script:
  - >-
    BUNDLE_GEMFILE=.overcommit_gems.rb bundle exec "overcommit --run" &&
    bundle exec rake spec

notifications:
  slack:
    secure: cTsubHjA23lK7Cgt2LhXyxV65UlA7hoaLRWSpXpYm6RNkqU9T8NZuSBnQj2OiDlzUc8jYn+m5Q/DLGmIhiA0jR5+Z24rHcUsfrd0t3czNCui0kajvimt2qbK5avV1jzEsVOBZVJ4B7LFtU0vwvGmGFDpP6jW8YS/MekABla9Y8Sf0TwVg6NmIhJm3PXYjrYyYHK+QADwg0JIQDiuxsvMvMLsf3j3Xk/cqVxxe3SuiX84UOvPvy2g7j520utuIPo6l7V6O1RcPjam98A7omMNrDc7VDHKj6BsLHVEVQ/WXjsLd6hvtelval7/F2QNVt9ySNd11arIwc2ga5yO1JkTbO1I5J58kszGUwJhRwmCY0kukvcpcbcoFTYzvR9ILGZ6P0RWEEAby5yOGdsiRqtI1eFEU4vutjxUOCoUOSZ8BCPlLdxM8sRyjzJ5HDeZhG6NNH6V9KKfrKIPP/vWBoVzMhRatg9k56pB9/d/F2K79e24kVPkWaASrImHE37Ne+uM8+1b0eYn4S56HQz9VTuYuAq3X1aiYrbep5AQ/p4LPi4RSS2janHixIrxuFKggLH8dJjnaDvSfZ6iopsaCZn06IZE0Cz0TVS4VOkwSBhjBnWWNN6bPVNJz665YjfxC/cPSZBVO58m+qRRB05El51x/F2UvIYaii6Tjgl22AkOArA=
addons:
  postgresql: "9.4"
  code_climate:
    repo_token: c97869f84431833f81de3c72b8c8a87e2e78f7d5b2f3ebe1278fedddc2a9cdbe
