language: ruby
cache: bundler
rvm: 2.3.0
env: RAILS_ENV=test DEVISE_MAILER_SENDER=no-reply@example.org SECRET_KEY_BASE=d2f5fb09a9b95e74af0c86eae84961c4440a483487e3237097c69ddfb9f4aa3bd482c352074cfcff369df51dddbb40e01932fa89585ba7e421ff3e5d62e23338

# Travis CI clones repositories to a depth of 50 commits, which is only really
# useful if you are performing git operations.
# https://docs.travis-ci.com/user/customizing-the-build/#Git-Clone-Depth
git:
  depth: 3

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libproj-dev
  - sudo apt-get install -y libffi-dev
  - gem install -v 1.17.3 bundler

before_script:
  - psql -c "CREATE DATABASE pafs_test WITH ENCODING 'UTF8';" -U postgres
  - cp $TRAVIS_BUILD_DIR/dotenv.travis $TRAVIS_BUILD_DIR/.env
  - cp $TRAVIS_BUILD_DIR/config/database.travis.yml $TRAVIS_BUILD_DIR/config/database.yml
  - cp config/secrets.yml.example config/secrets.yml
  - bundle exec rake db:schema:load RAILS_ENV=test
  - git config --global user.name "Travis Test"
  - git config --global user.email travis@example.com

script:
  - bundle exec rake spec

notifications:
  slack:
    secure: SXYpp+HFF58LI4vULoNW9LSqKCNXPaAXsYCKHAK3tITrFvAsuVOhoaQQNOdbRQfEkqb4cG8+gtp7v4W+SUjWU3BsMTd9AP9BsBz8aICLzI30yRy51htN40lCQLnSsFRb8pYeSkHjIzHJdWhT4Zx3jFbOQiH7KfEx2xYL/YqbgGVm/LKqXszGdaAivjOU2SF9+r6yK+5Ysub4V6x3AOPJN91pO1KyzhaNWyrI9j6mbNBhMfpC8Kf9zFtjwmCeFsfqASm9xZsSum7bAQPHCT9bi2qrMn4uiewA+uE5gIVgimAVBvXII1GbY/BYn9P7IU2EzHzHoTYbX5Q0ixFpqPE+HNHuFeKbxULD8e1+Dv0Rtu5RZtxndY94q9CSDrlDbaKNPpS9lt4cWdnMp1/7F4XJ7hJsyWsKmxwK0+oA5ma9G0SdpATk5FgVL2OLdPwuUab38Tjmm1zGU8EdQw8QrgIaiLnR/8ImghmnozfB/ILYOpcR+zGopBbrCtjzNsBCq91ZdDvpm/Hcghfj1O3t3xZs9JEAGRaPOKbhIgy2EsCmJPHRdj/bTEFgrmUZi00RnlWvK8CqomkSE49ToyCawhyTUDWrXuv+ljWDF1r1LXxxkP5AnwxsczhY3K17eY/rfp16uLTi1wOxYpaQ0LyN/0WYBcaEOt60D8UySDPUKygipFo=
addons:
  postgresql: '9.5'
  code_climate:
    repo_token: c97869f84431833f81de3c72b8c8a87e2e78f7d5b2f3ebe1278fedddc2a9cdbe
