name: Continuous Integration Tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install application dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y libpq-dev
          sudo apt-get install -y libproj-dev
          sudo apt-get install -y libffi-dev
          sudo gem install bundler

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      
      - name: Run tests
        run: |
          psql -c "CREATE DATABASE pafs_test WITH ENCODING 'UTF8';" -U postgres
        
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}