name: Continuous Integration Tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY_BASE: somescarylongvaluefullofnumbersandlettersi
      DATABASE_USERNAME: username
      DATABASE_PASSWORD: password
      DEVISE_USER_SEPARATE_DB: false
      DEVISE_MAILER_SENDER: no-reply@example.org
      AIRBRAKE_HOST: https://errbit.server.here
      AIRBRAKE_PROJECT_KEY: errbit_project_key_here
      GOOGLE_ANALYTICS_ID: your-id-here
      EMAIL_USERNAME: george.schena@defra.gov.uk
      EMAIL_PASSWORD: bob
      EMAIL_HOST: localhost
      EMAIL_PORT: 1025

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_USER: username
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install application dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y libproj-dev
          sudo apt-get install -y libffi-dev
          sudo gem install bundler

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      
      - name: Run tests
        run: |
          sudo service postgresql start
          psql -c "CREATE DATABASE pafs_test WITH ENCODING 'UTF8';"
          bundle exec rake db:seed RAILS_ENV=test
          bundle exec rspec